Update csm-release-libs.yaml

diff --git a/.github/workflows/csm-release-libs.yaml b/.github/workflows/csm-release-libs.yaml
--- a/.github/workflows/csm-release-libs.yaml
+++ b/.github/workflows/csm-release-libs.yaml
@@ -22,27 +22,27 @@ jobs:
     name: Build, Scan and Release
     runs-on: ubuntu-latest    
     steps:
-      - name: Validate version input
-        run: |
-          if [[ "${{ github.event.inputs.version }}" == "none" ]]; then
-            echo "Invalid version specified: ${{ github.event.inputs.version }} Must follow major, minor, patch versioning."
-            exit 1
-          fi
-      - name: Checkout the code
-        uses: actions/checkout@v4
-      - name: Set up Go
-        uses: actions/setup-go@v5
-        with:
-          go-version: "1.23"
-      - name: Install dependencies
-        run: go mod tidy
-      - name: Build
-        run: go build -v ./...
-      - name: Run malware scan
-        uses: dell/common-github-actions/malware-scanner@main
-        with:
-          directories: .
-          options: -ri
+      # - name: Validate version input
+      #   run: |
+      #     if [[ "${{ github.event.inputs.version }}" == "none" ]]; then
+      #       echo "Invalid version specified: ${{ github.event.inputs.version }} Must follow major, minor, patch versioning."
+      #       exit 1
+      #     fi
+      # - name: Checkout the code
+      #   uses: actions/checkout@v4
+      # - name: Set up Go
+      #   uses: actions/setup-go@v5
+      #   with:
+      #     go-version: "1.23"
+      # - name: Install dependencies
+      #   run: go mod tidy
+      # - name: Build
+      #   run: go build -v ./...
+      # - name: Run malware scan
+      #   uses: dell/common-github-actions/malware-scanner@main
+      #   with:
+      #     directories: .
+      #     options: -ri
 
       - name: Import GPG key
         uses: crazy-max/ghaction-import-gpg@v6
